In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle

In [4]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [7]:
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
data=pd.concat([data.drop("Geography",axis=1),geo_encoded_df],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
X=data.drop("EstimatedSalary",axis=1)
y=data["EstimatedSalary"]

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
model=Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)),
    Dense(32,activation="relu"),
    Dense(1)
])
model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2,945
Trainable params: 2,945
Non-trainable params: 0
_________________________________________________________________

In [15]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime
# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [16]:
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [17]:
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 100379.1016 - mae: 100379.1016 - val_loss: 98520.7109 - val_mae: 98520.7109
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99633.4297 - mae: 99633.4297 - val_loss: 96986.7188 - val_mae: 96986.7188
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 96956.1562 - mae: 96956.1562 - val_loss: 93018.2422 - val_mae: 93018.2422
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 91663.9766 - mae: 91663.9766 - val_loss: 86420.1016 - val_mae: 86420.1016
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 83960.8438 - mae: 83960.8438 - val_loss: 77826.6172 - val_mae: 77826.6172
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 74801.9219 - mae: 74801.9219 - val_loss: 68824.4297 - val_mae: 68824.4297
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 65925.2500 - mae: 65925.2500 - val_loss: 61114.5039 - val_mae: 61114.5039
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 58826.4453 - mae: 58826.4453 - val_loss: 55744.2383 - val_mae: 55744.2383
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 54222.9297 - mae: 54222.9297 - val_loss: 52554.9961 - val_mae: 52554.9961
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 51796.5039 - mae: 51796.5039 - val_loss: 51299.2539 - val_mae: 51299.2539
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 50782.1836 - mae: 50782.1836 - val_loss: 50861.7109 - val_mae: 50861.7109
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50374.6523 - mae: 50374.6523 - val_loss: 50725.2031 - val_mae: 50725.2031
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 50200.6055 - mae: 50200.6055 - val_loss: 50662.7188 - val_mae: 50662.7188
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50109.3281 - mae: 50109.3281 - val_loss: 50624.8750 - val_mae: 50624.8750
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50049.0508 - mae: 50049.0508 - val_loss: 50587.7852 - val_mae: 50587.7852
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 49996.2812 - mae: 49996.2812 - val_loss: 50559.0508 - val_mae: 50559.0508
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 49958.6797 - mae: 49958.6797 - val_loss: 50543.8086 - val_mae: 50543.8086
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 49921.6797 - mae: 49921.6797 - val_loss: 50502.2695 - val_mae: 50502.2695
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 49887.8008 - mae: 49887.8008 - val_loss: 50468.4727 - val_mae: 50468.4727
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 49862.3203 - mae: 49862.3203 - val_loss: 50452.0703 - val_mae: 50452.0703
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49831.0625 - mae: 49831.0625 - val_loss: 50431.9414 - val_mae: 50431.9414
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49808.9961 - mae: 49808.9961 - val_loss: 50419.9531 - val_mae: 50419.9531
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 49787.7070 - mae: 49787.7070 - val_loss: 50410.9766 - val_mae: 50410.9766
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49768.4375 - mae: 49768.4375 - val_loss: 50400.8789 - val_mae: 50400.8789
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49749.4023 - mae: 49749.4023 - val_loss: 50380.6094 - val_mae: 50380.6094
Epoch 26/100
250/250 [==============================] - 1s 2ms/step - loss: 49734.5195 - mae: 49734.5195 - val_loss: 50364.4297 - val_mae: 50364.4297
Epoch 27/100
250/250 [==============================] - 1s 2ms/step - loss: 49716.6797 - mae: 49716.6797 - val_loss: 50362.3789 - val_mae: 50362.3789
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49702.1758 - mae: 49702.1758 - val_loss: 50348.7148 - val_mae: 50348.7148
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 49686.0898 - mae: 49686.0898 - val_loss: 50344.1562 - val_mae: 50344.1562
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49668.7578 - mae: 49668.7578 - val_loss: 50342.0898 - val_mae: 50342.0898
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 49658.0352 - mae: 49658.0352 - val_loss: 50335.5391 - val_mae: 50335.5391
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49646.4805 - mae: 49646.4805 - val_loss: 50324.9844 - val_mae: 50324.9844
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49629.7109 - mae: 49629.7109 - val_loss: 50320.8555 - val_mae: 50320.8555
Epoch 34/100
250/250 [==============================] - 1s 2ms/step - loss: 49620.0703 - mae: 49620.0703 - val_loss: 50316.8398 - val_mae: 50316.8398
Epoch 35/100
250/250 [==============================] - 1s 2ms/step - loss: 49611.5391 - mae: 49611.5391 - val_loss: 50316.1094 - val_mae: 50316.1094
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 49602.1680 - mae: 49602.1680 - val_loss: 50304.3398 - val_mae: 50304.3398
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49588.5039 - mae: 49588.5039 - val_loss: 50292.5469 - val_mae: 50292.5469
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 49577.5469 - mae: 49577.5469 - val_loss: 50295.8906 - val_mae: 50295.8906
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49571.8633 - mae: 49571.8633 - val_loss: 50302.5312 - val_mae: 50302.5312
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49563.5117 - mae: 49563.5117 - val_loss: 50297.5078 - val_mae: 50297.5078
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 49553.5234 - mae: 49553.5234 - val_loss: 50293.6875 - val_mae: 50293.6875
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49545.6797 - mae: 49545.6797 - val_loss: 50284.3906 - val_mae: 50284.3906
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 49533.0508 - mae: 49533.0508 - val_loss: 50276.3984 - val_mae: 50276.3984
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 49529.3086 - mae: 49529.3086 - val_loss: 50278.8281 - val_mae: 50278.8281
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 49520.0938 - mae: 49520.0938 - val_loss: 50281.0586 - val_mae: 50281.0586
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49510.9531 - mae: 49510.9531 - val_loss: 50276.8945 - val_mae: 50276.8945
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 49501.6758 - mae: 49501.6758 - val_loss: 50283.1133 - val_mae: 50283.1133
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49499.9688 - mae: 49499.9688 - val_loss: 50280.8906 - val_mae: 50280.8906
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49489.1680 - mae: 49489.1680 - val_loss: 50277.8477 - val_mae: 50277.8477
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 49482.4688 - mae: 49482.4688 - val_loss: 50281.1367 - val_mae: 50281.1367
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 49475.6758 - mae: 49475.6758 - val_loss: 50271.0625 - val_mae: 50271.0625
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49469.5508 - mae: 49469.5508 - val_loss: 50272.0547 - val_mae: 50272.0547
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 49460.8359 - mae: 49460.8359 - val_loss: 50275.2656 - val_mae: 50275.2656
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 49454.7305 - mae: 49454.7305 - val_loss: 50287.4219 - val_mae: 50287.4219
Epoch 55/100
250/250 [==============================] - 1s 2ms/step - loss: 49449.6172 - mae: 49449.6172 - val_loss: 50271.9844 - val_mae: 50271.9844
Epoch 56/100
250/250 [==============================] - 1s 2ms/step - loss: 49444.4727 - mae: 49444.4727 - val_loss: 50292.1094 - val_mae: 50292.1094
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 49436.7266 - mae: 49436.7266 - val_loss: 50287.8281 - val_mae: 50287.8281
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 49433.4609 - mae: 49433.4609 - val_loss: 50286.2305 - val_mae: 50286.2305
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 49426.1562 - mae: 49426.1562 - val_loss: 50295.9141 - val_mae: 50295.9141
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49423.9961 - mae: 49423.9961 - val_loss: 50300.9023 - val_mae: 50300.9023
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 49416.0234 - mae: 49416.0234 - val_loss: 50301.6367 - val_mae: 50301.6367

In [18]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit